INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('ADMIN', 'Administrador del sistema');
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('USER', 'Usuario estándar del sistema');
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('LAB_TECH', 'Técnico de laboratorio');

INSERT INTO USERS (USERNAME,PASSWORD,CREATED_AT) VALUES ('ADMIN','$2a$10$oxg0N48e2/zdKUhkXaD93O3Q06C9a9z4yCsWJovOCcoUtsWpTeEoy',NOW());